In [343]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
baseball = pd.read_csv('/content/최종KIA.csv', encoding='UTF-8')
baseball.head()

,num,enddate,end+1,target,target2,Start Date,End Date,#,팀명,경기,...,상대연봉,연봉차,내자산,상대자산,자산차,홈 경기수,어웨이 경기수,평균 관중수,평균 이동거리,누적 이동거리
0,1,6,7,0,lose,2024-03-23,2024-03-29,1,KIA,4,...,13988,176,177.9,26.9,151.0,0,6,0.00000,1710,1710
1,12,7,8,1,win,2024-03-24,2024-03-30,2,KIA,4,...,13988,176,177.9,26.9,151.0,1,5,14233.00000,1410,1410
2,22,8,9,0,lose,2024-03-26,2024-03-31,2,KIA,5,...,17038,-2874,177.9,46.8,131.1,2,4,17366.50000,1110,1110
3,34,9,10,1,win,2024-03-27,2024-04-02,4,KIA,5,...,17038,-2874,177.9,46.8,131.1,3,3,18283.66667,900,900
4,45,10,11,1,win,2024-03-28,2024-04-03,5,KIA,5,...,17038,-2874,177.9,46.8,131.1,5,1,18422.80000,300,300

In [220]:
# '차_타율'
# '차_ERA'
# '차_WHIP'
# '차_OPS'
# '차_장타율'
# '차_출루율'
# '차_안타'
# '연봉차'
# '자산차'
# '투_ERA'
# '투_FIP'
# '투_WHIP'
# '투_볼넷율'
# '투_이닝당타자'
# '타_BABIP'
# '타_OPS'
# '안타+탈삼진/피안타+삼진'
# '탈삼진/삼진'
# '안타/피안타'
# '차_타석'

In [344]:
# 이 species 열을 target으로 만들고 입력 데이터로 사용할 컬럼명 넣기.
# baseball_input = baseball[['타_출루율', '투_이닝당타자', '차_OPS', '연봉차',  '차_타석', '투_볼넷율']].to_numpy()
baseball_input = baseball[['타_장타율', '차_OPS',  '연봉차',  '투_볼넷율', '투_이닝당타자']].to_numpy()
print(baseball_input[:5])
baseball_target = baseball['target2'].to_numpy()

[[ 4.3900000e-01  1.7000000e-02  1.7600000e+02  1.2100000e-01
   4.1390000e+00]
 [ 3.5400000e-01 -1.8246841e-01  1.7600000e+02  1.6200000e-01
   4.4000000e+00]
 [ 3.8900000e-01 -3.0568446e-02 -2.8740000e+03  1.4900000e-01
   4.4090000e+00]
 [ 4.1200000e-01 -2.4435554e-02 -2.8740000e+03  1.5200000e-01
   4.5810000e+00]
 [ 4.0700000e-01  3.9317019e-02 -2.8740000e+03  1.4300000e-01
   4.5580000e+00]]

In [345]:
# KNeighborsClassifier 클래스 객체를 만들고 훈련셋으로 훈련한 다음 점수를 각각 확인해본다. k는 3으로 지정.
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled, train_target)

print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))
print("")

0.7160493827160493
0.5

In [346]:
# 훈련셋과 테스트셋으로 나누기
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(baseball_input, baseball_target, random_state = 31)
# StandardScaler 클래스로 표준화 전처리


# 훈련셋  통계값으로 테스트셋을 변환해야 함.
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)
baseball_indexes = (train_target == 'win') | (train_target == 'lose')
train_logi = train_scaled[baseball_indexes]
target_logi = train_target[baseball_indexes]

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=10, max_iter=1000)
lr.fit(train_scaled, train_target)
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))
print("")

# 로지스틱 회귀가 학습한 계수를 확인해본다.
print(lr.coef_, lr.intercept_)

0.6071428571428571
0.5862068965517241

[[ 0.38521451 -0.39896831  0.14161979  0.12222565  0.20534862]] [0.2518682]